# Source-tracking POMDP
N_DIMS = 2
LAMBDA_OVER_DX = 2.0
R_DT = 2.0

# Neural network architecture
FC_LAYERS = 3
FC_UNITS = 128

# Restart from saved model
MODEL_PATH = None





# TESTING
N_DIMS = 1
N_GRID = 11
STOP_t = 50
FC_LAYERS = 3
MEMORY_SIZE = 1000
EVALUATE_PERFORMANCE_EVERY = 3
N_RUNS_STATS = 10
BATCH_SIZE = 12
REPLAY_NTIMES = 4
SAVE_MODEL_EVERY = 2
N_GD_STEPS = 100
ALGO_MAX_IT = 10
SYM_EVAL_ENSEMBLE_AVG = False
SYM_TRAIN_ADD_DUPLICATES = False
SYM_TRAIN_RANDOMIZE = False
PRINT_INFO_EVERY = 2